// para que agreguen sus variables de entorno en .env

GOOGLE_CLIENT_ID = 
GOOGLE_CLIENT_SECRET = 
CALLBACK_URL_GOOGLE = 
FACEBOOK_CLIENT_ID = 
FACEBOOK_CLIENT_SECRET = 
CALLBACK_URL_FACEBOOK = 
LINKEDIN_CLIENT_ID = 
LINKEDIN_CLIENT_SECRET = 
CALLBACK_URL_LINKEDIN = 
GITHUB_CLIENT_ID = 
GITHUB_CLIENT_SECRET = 
CALLBACK_URL_GITHUB = 